/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Carousel: typeof import('./src/components/common/Carousel.vue')['default']
    CarouselCard: typeof import('./src/components/common/CarouselCard.vue')['default']
    DefaultLayout: typeof import('./src/components/layoutWrapper/DefaultLayout.vue')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    FullWidthLayout: typeof import('./src/components/layoutWrapper/FullWidthLayout.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    Loading: typeof import('./src/components/common/Loading.vue')['default']
    Login: typeof import('./src/components/login/index.vue')['default']
    MemberMenu: typeof import('./src/components/common/MemberMenu.vue')['default']
    Modal: typeof import('./src/components/common/Modal.vue')['default']
    MyButton: typeof import('./src/components/common/MyButton.vue')['default']
    NoneHeader: typeof import('./src/components/layoutWrapper/noneHeader.vue')['default']
    Oauth: typeof import('./src/components/Oauth.vue')['default']
    Pagination: typeof import('./src/components/common/Pagination.vue')['default']
    PlanCard: typeof import('./src/components/common/PlanCard.vue')['default']
    PlanList: typeof import('./src/components/common/PlanList.vue')['default']
    ProductCard: typeof import('./src/components/common/ProductCard.vue')['default']
    ProductCardList: typeof import('./src/components/common/ProductCardList.vue')['default']
    ProgressBar: typeof import('./src/components/common/ProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareButton: typeof import('./src/components/common/ShareButton.vue')['default']
    Signup: typeof import('./src/components/signup/index.vue')['default']
    Tag: typeof import('./src/components/common/Tag.vue')['default']
    ToCartPlanCard: typeof import('./src/components/common/ToCartPlanCard.vue')['default']
    Upload: typeof import('./src/components/common/Upload.vue')['default']
  }
}
