// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/common/Button.vue')['default']
    DefaultLayout: typeof import('./src/components/layoutWrapper/DefaultLayout.vue')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    MemberMenu: typeof import('./src/components/common/MemberMenu.vue')['default']
    Modal: typeof import('./src/components/common/Modal.vue')['default']
    NoneHeader: typeof import('./src/components/layoutWrapper/noneHeader.vue')['default']
    PlanCard: typeof import('./src/components/common/PlanCard.vue')['default']
    PlanList: typeof import('./src/components/common/PlanList.vue')['default']
    ProgressBar: typeof import('./src/components/common/ProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareButton: typeof import('./src/components/common/ShareButton.vue')['default']
    Upload: typeof import('./src/components/common/Upload.vue')['default']
  }
}
